### ISSUE TITLE
horizontal scrolling breaks on narrow window size

### ISSUE THREAD

**Issue by cowills** [rei/rei-cedar-docs#349]
![small](https://user-images.githubusercontent.com/48567940/59533197-9e66eb00-8e9f-11e9-855e-212f0dcc5a10.gif)

ifl this should be fixable with a couple lines of css 🤔 it's triggered anytime there is a horizontal overflow of content

**Comment by mhewson** [comment]
I agree that this is an easy fix working on prioritizing some doc site updates now
